services:
  queue-image:
    image: queue-image:latest
    pull_policy: never
    build:
      context: .
      dockerfile: Dockerfile

  db:
    image: 'postgres:13'
    container_name: db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=queue
      - POSTGRES_PASSWORD=queue
      - POSTGRES_DB=queue

  db-init:
    image: queue-image:latest
    pull_policy: never
    command: ['npm', 'run', 'db:migration:up']
    restart: on-failure:5
    depends_on:
      - db
      - queue-image

  queue-service:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
            - package.json
            - package-lock.json
        - action: rebuild
          path: ./package.json
    ports:
      - '8080:8080'
    command: ['npm', 'run', 'dev:start']
    depends_on:
      db-init:
        condition: service_completed_successfully
